### ISSUE TITLE
about delayed upload of nse future bhavcopy

### ISSUE THREAD

**Issue by kalyan4512** [virresh/nseeod#5]
recently one issue either nse cash indices or nse future bhavcopy uploaded lately on the same day around 11pm.  www1.nseindia.com. so data download problem. did u notice such issue?

**Comment by kalyan4512** [comment]
i think nse is now will upload future bhavcopy in nseindia.com ,not in www1.nseindia.com.
already seen that future  bhavcipy is uploaded for today in nseindia.com.
just giving feed back. dont know they will upload it in www1nseindia.com

**Comment by virresh** [comment]
Thanks for the feedback. 
I have incorporated this suggestion and will provide three different configurations to choose from, so I hope this would not be an issue :sweat_smile: 

The new software is almost ready. I will launch it by this weekend if everything goes right :D 

Will appreciate your feedback on the new version then.

**Comment by virresh** [comment]
Hi @kalyan4512 ,
I've released the new software today.

Find the details at: https://github.com/virresh/StockD#steps-to-run-for-users

Also, created a new chatroom for users interested in connecting with each other. Join at https://gitter.im/virresh/StockD .
I'll be monitoring the new repository now, since this codebase is old

**Comment by kalyan4512** [comment]
pls also  answer issues regarding nseeodfixed as  ur recent version is for
64 bit and  not working in m system as i have 32 bit window 7.. also try to
bring 32 bit version for ur recent version.
java is still giving version 8 and we may not update if java 9 introduced

**Comment by virresh** [comment]
@kalyan4512

I've released v4.1 for StockD here: https://github.com/virresh/StockD/releases/tag/4.1

It supports both Windows 32bit and 64bit
Hope that solves your problem

Fixing nseeod is not feasible because I need to use some libraries that only support > Java 9. And Java 9 does not support 32 bit. See this tweet by Java's Chief Architect at Oracle here: https://twitter.com/mreinhold/status/912311207935090689

So you will never get Java 9. In order to bring Java 9 to 32-bit users, I'll have to build it on my own for all platforms and I don't have the bandwidth to do that
